version: '3.8'

services:
  backchannels-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODEL_THRESHOLD=0.949
      - MAX_BATCH_SIZE=32
      - LOG_LEVEL=INFO
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount model weights if they're large (uncomment if needed)
      # - ./app/models/weights:/app/app/models/weights
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
