version: '3.8'

services:
  backchannels-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Model fallback configuration
      - PREFERRED_MODEL=distilbert-onnx
      - FALLBACK_MODEL=baseline
      - ENABLE_FALLBACK=true
      # Model configuration
      - MODEL_THRESHOLD=0.949
      # API configuration
      - MAX_BATCH_SIZE=32
      # Logging configuration
      - LOG_LEVEL=INFO
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
      # Mount model weights if they're large (uncomment if needed)
      # - ./app/models/weights:/app/app/models/weights
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G  # Increased memory for model loading
          cpus: '2.0'  # 2 CPU cores for better throughput
        reservations:
          memory: 2G
          cpus: '1.0'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
